// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOBCZ_3K17VS_08Y9X7DzNZTSzDl0cq4',
    appId: '1:210097262184:web:68d8ad0c6a8aaa2505f5dd',
    messagingSenderId: '210097262184',
    projectId: 'library-heaven-mobile',
    authDomain: 'library-heaven-mobile.firebaseapp.com',
    storageBucket: 'library-heaven-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFVP4clGuwk8WPGh7j5rt6Fxq1FXepXc',
    appId: '1:210097262184:android:c7799039f6ceee7e05f5dd',
    messagingSenderId: '210097262184',
    projectId: 'library-heaven-mobile',
    storageBucket: 'library-heaven-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3cCMMEEf76gBwr_OA2OKnJzWlle2haXo',
    appId: '1:210097262184:ios:8574075ca76a45ee05f5dd',
    messagingSenderId: '210097262184',
    projectId: 'library-heaven-mobile',
    storageBucket: 'library-heaven-mobile.firebasestorage.app',
    iosBundleId: 'com.example.literaryHeaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3cCMMEEf76gBwr_OA2OKnJzWlle2haXo',
    appId: '1:210097262184:ios:8574075ca76a45ee05f5dd',
    messagingSenderId: '210097262184',
    projectId: 'library-heaven-mobile',
    storageBucket: 'library-heaven-mobile.firebasestorage.app',
    iosBundleId: 'com.example.literaryHeaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZOBCZ_3K17VS_08Y9X7DzNZTSzDl0cq4',
    appId: '1:210097262184:web:e06bd63716f5c48d05f5dd',
    messagingSenderId: '210097262184',
    projectId: 'library-heaven-mobile',
    authDomain: 'library-heaven-mobile.firebaseapp.com',
    storageBucket: 'library-heaven-mobile.firebasestorage.app',
  );

}