// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8TwEhMoUhG9ul69E9T4-Zht3Dd3JewqU',
    appId: '1:708889484889:web:9840889904c1d461479b48',
    messagingSenderId: '708889484889',
    projectId: 'project-literary-haven-564e4',
    authDomain: 'project-literary-haven-564e4.firebaseapp.com',
    storageBucket: 'project-literary-haven-564e4.firebasestorage.app',
    measurementId: 'G-M1G45DZT69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcubwHzx8lYoZ6pK7sNjCsO-2SjIo4jU',
    appId: '1:708889484889:android:32839cb016ad49d5479b48',
    messagingSenderId: '708889484889',
    projectId: 'project-literary-haven-564e4',
    storageBucket: 'project-literary-haven-564e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9mwoi5Tri3UrlSetT-Dx1eB30_RcdPo',
    appId: '1:708889484889:ios:f987c1b687523e52479b48',
    messagingSenderId: '708889484889',
    projectId: 'project-literary-haven-564e4',
    storageBucket: 'project-literary-haven-564e4.firebasestorage.app',
    iosBundleId: 'com.example.literaryHeaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu9mwoi5Tri3UrlSetT-Dx1eB30_RcdPo',
    appId: '1:708889484889:ios:f987c1b687523e52479b48',
    messagingSenderId: '708889484889',
    projectId: 'project-literary-haven-564e4',
    storageBucket: 'project-literary-haven-564e4.firebasestorage.app',
    iosBundleId: 'com.example.literaryHeaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8TwEhMoUhG9ul69E9T4-Zht3Dd3JewqU',
    appId: '1:708889484889:web:772a3c6b038bdad6479b48',
    messagingSenderId: '708889484889',
    projectId: 'project-literary-haven-564e4',
    authDomain: 'project-literary-haven-564e4.firebaseapp.com',
    storageBucket: 'project-literary-haven-564e4.firebasestorage.app',
    measurementId: 'G-N19BF9M8ZS',
  );
}
